version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.django
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    restart: always
    read_only: true
    networks:
      - backend
    environment:
      - DJANGO_SETTINGS_MODULE=GoodBiteBackend.settings.local

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx  # Montamos los logs
      - ./docker/nginx/ssl:/app
      - static_volume:/app/staticfiles
    restart: always
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
    driver: bridge
