# Generated by Django 5.2 on 2025-08-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrochemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('measurement_unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('g', 'Gram')], default='kg', max_length=2, verbose_name='measurement unit')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
            ],
            options={
                'verbose_name': 'agrochemical',
                'verbose_name_plural': 'agrochemicals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KindAgrochemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Kind of Agrochemical',
                'verbose_name_plural': 'Kinds of Agrochemicals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='dosage')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('g', 'Gram')], default='ml', max_length=10, verbose_name='unit')),
                ('responsible', models.CharField(max_length=100, verbose_name='responsible')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('agrochemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_controls', to='health.agrochemical', verbose_name='agrochemical')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots_controls', to='production.plot', verbose_name='plot')),
            ],
            options={
                'verbose_name': 'chemical control',
                'verbose_name_plural': 'chemical controls',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='agrochemical',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='health.kindagrochemical', verbose_name='kind'),
        ),
    ]
