# docker/Dockerfile.django

FROM python:3.12-slim-bookworm

# Seguridad y consistencia
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DEFAULT_TIMEOUT=100

# Instala dependencias del sistema necesarias
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    gettext \
    && rm -rf /var/lib/apt/lists/*

# Crea un usuario no root para seguridad
RUN useradd -m appuser

WORKDIR /app

# Solo copia lo necesario (usa .dockerignore también)
COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Luego copia el resto del código (evita copiar archivos secretos)
COPY . .

# Crea directorios de estáticos y media y asigna permisos
RUN mkdir -p /app/staticfiles && \
    chown -R appuser:appuser /app

# Compilar mensajes como root
RUN django-admin compilemessages

# Usa usuario no root
USER appuser

# Expón el puerto
EXPOSE 8000

CMD ["gunicorn", "--worker-tmp-dir", "/dev/shm","-b", "0.0.0.0:8000", "djangoProjects.wsgi"]