# Generated by Django 5.2 on 2025-08-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total earnings')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('price_per_hundred', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per hundred')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='farming.distribution', verbose_name='distribution')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hundred', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per hundred')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total price')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('distribution', models.OneToOneField(limit_choices_to={'type': 'sale'}, on_delete=django.db.models.deletion.CASCADE, to='farming.distribution', verbose_name='distribution')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='sales.salev2', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'distribution',
                'verbose_name_plural': 'distributions',
                'ordering': ['-sale__date'],
            },
        ),
    ]
