# Generated by Django 5.2 on 2025-08-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('date_planted', models.DateField(verbose_name='date planted')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
            ],
            options={
                'verbose_name': 'plot',
                'verbose_name_plural': 'plots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='height_m')),
                ('date_planted', models.DateField(verbose_name='date_planted')),
                ('age_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='age_years')),
                ('status', models.CharField(choices=[('healthy', 'healthy'), ('diseased', 'diseased'), ('dead', 'dead')], default='healthy', max_length=20, verbose_name='status')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='production.plot', verbose_name='plot')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='production.species', verbose_name='species')),
            ],
            options={
                'verbose_name': 'tree',
                'verbose_name_plural': 'trees',
                'ordering': ['plot', 'species'],
            },
        ),
    ]
