# Generated by Django 5.2 on 2025-08-29 22:25

import django.db.models.deletion
import packages.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='harvest date')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('measurement', models.CharField(choices=[('kg', 'Kilograms'), ('l', 'Liters'), ('h', 'Hundreds'), ('u', 'Units')], default='u', max_length=2, verbose_name='measurement')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.plot', verbose_name='plot')),
            ],
            options={
                'verbose_name': 'harvest',
                'verbose_name_plural': 'harvests',
                'ordering': ['-harvest_date'],
            },
            bases=(models.Model, packages.core.mixins.QuantityDisplayMixin),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(verbose_name='distribution date')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('measurement', models.CharField(choices=[('kg', 'Kilograms'), ('l', 'Liters'), ('h', 'Hundreds'), ('u', 'Units')], default='u', max_length=2, verbose_name='measurement')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('family', 'Family'), ('discard', 'Discard')], default='sale', max_length=10, verbose_name='type')),
                ('quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20, null=True, verbose_name='quality')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.harvest', verbose_name='harvest')),
            ],
            options={
                'verbose_name': 'distribution',
                'verbose_name_plural': 'distributions',
                'ordering': ['-distribution_date'],
            },
            bases=(models.Model, packages.core.mixins.QuantityDisplayMixin),
        ),
    ]
